### ISSUE TITLE
Attendee Interface - Audio Visual Notification System

### ISSUE THREAD

**Issue by DrewTCurrie** [Direxfire/55ATAT#16]
> [!IMPORTANT]  
> Play some audio and visual notification for successful and unsuccessful check-ins 
> Why: Completion is required to reach SPD

---

**Feature needed:**
Adding support for audio and visual notification for the check-in process. This will allow Attendees to know they checked-in successfully and allow an employee to hear/see if there was an issue with a check-in and intervene.

**Comment by samlovering** [comment]
For whoever picks this up. I intend for these elements to be changeable through an administrator control panel. Can this be setup in a way that it selects display settings from the backend?
