### ISSUE TITLE
Report Generation - Comments not appearing in Report

### ISSUE THREAD

**Issue by samlovering** [Direxfire/55ATAT#18]
At the moment, comments are not assigned to attendance events in the report generation program.

At the moment it just prints a timestamp.

I don't have a screenshot, but to recreate:
1. Have some attendance events with comments
2. Attempt to generate a report..
3. View a commented event on the repot.
These only display timestamps when it should be the comment.

**Comment by DrewTCurrie** [comment]
Check this is working after #33

**Comment by DrewTCurrie** [comment]
Confirmed working in most recent dev after #45 seems like #33 did fix it. 
![CommentsTest](https://github.com/user-attachments/assets/258cb4d3-169e-48be-ba3c-aa1aac946cab)
