### ISSUE TITLE
Webpage - Signing in as Admin will automatically reroute to events page

### ISSUE THREAD

**Issue by DrewTCurrie** [Direxfire/55ATAT#43]
When you go to sign in as an admin and are trying to access the clients page, the webpage will reroute you to the events page.

**Comment by samlovering** [comment]
Question on this, where should this route to? At the moment its setup to navigate to the Events page upon successful login.

**Comment by DrewTCurrie** [comment]
Yeah I can't think of anything better anyway. So I think this is fine, closing as we don't need to fix.
